version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - "8080:81"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password

  web:
    build: .
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - mysql
